const DELAY_BETWEEN_FILE_EXECUTION = 100;

const DEFAULT_FILENAME = 'index.js';

const CHOKIDAR_ADD = 'add';
const CHOKIDAR_CHANGE = 'change';
const CHOKIDAR_UNLINK = 'unlink';

module.exports.DELAY_BETWEEN_FILE_EXECUTION = DELAY_BETWEEN_FILE_EXECUTION;
module.exports.DEFAULT_FILENAME = DEFAULT_FILENAME;
module.exports.CHOKIDAR_ADD = CHOKIDAR_ADD;
module.exports.CHOKIDAR_CHANGE = CHOKIDAR_CHANGE;
module.exports.CHOKIDAR_UNLINK = CHOKIDAR_UNLINK;
